### ISSUE TITLE
loot.yml path

### ISSUE THREAD

**Issue by Platinteufel** [2008Choco/DragonEggDrop#1]
First of all thank you very much for this update! It's really awesome that it works in Minecraft 1.11.2 now! ;-)
It seems like you've changed the path for loot entries, so that the "old" loot.yml is not usable without changing the path of all entries. It's not a big issue, but maybe it's confusing for some users. 

"Old" path:
`  ? ==: com.ninjaguild.dragoneggdrop.LootEntry`
Path in your version:
`  ? ==: com.ninjaguild.dragoneggdrop.loot.LootEntry`

Best regards!

**Comment by 2008Choco** [comment]
Hm... didn't take that into consideration. Though I'm not sure I can fix something like that. I suppose it makes sense; the ? == variable defines the path to the class that was serialized, by the ConfigurationSerializable interface. I mean, worst case scenario, people Ctrl + F and replace all entries with "com.ninjaguild.dragoneggdrop.LootEntry" with "com.ninjaguild.dragoneggdrop.loot.LootEntry". Some people may not understand that, but I presume they'll notice that loot is not being generated properly.

Glad to know everything works in 1.11.2 though! That was the only version I had the willpower to test it on :P

**Comment by Platinteufel** [comment]
Maybe, yes. Sure, that's changed within 3 seconds .. it's easy if you know the answer. :p
After upgrading it told me that it can't generate a loot chest because my loot.yml is empty. I've double checked the file, but all entries were still there. After generating a new one I've noticed this little difference in the path.
Well, you don't need to change anything here, it works like a charm, but I wanted to share it with the other people. ;-)
