### ISSUE TITLE
Keep saying its not up to date

### ISSUE THREAD

**Issue by Zed9K** [2008Choco/DragonEggDrop#15]
Hello, i would like to report that this plugin keep saying its not up to date,
i use the 1.12.2 one, so its the latest for 1.12.2 
can you fix that ? its really annoying, its spammy in the console,
Thanks.

**Comment by 2008Choco** [comment]
`perform-update-checks` can be set to `false` in the config.yml of DragonEggDrop to disable update checks and notifications. It is recommended that this be done instead.
