### ISSUE TITLE
[Request] Placeholder for MVP

### ISSUE THREAD

**Issue by momoservertw** [2008Choco/DragonEggDrop#17]
Hello!
Can you add some placeholder that based on the damage to the dragon?
So that we can custom lots of reward commands and not only give the reward to one player.

It would be great if the plugin support PlaceholderAPI.
So the dragon killed information can show in other menu plugin.
https://www.spigotmc.org/wiki/hooking-into-placeholderapi/

Example placeholders.
%dragoneggdrop_dragon%
%dragoneggdrop_respawn_time% - Next dragon respawn time.

%dragoneggdrop_killer% - The one who killed the dragon
%dragoneggdrop_damagedtop_name_[1-5]% - The top 5 players who give the most damage to the dragon
%dragoneggdrop_damagedtop_percent_[1-5]% - The proportion of damage caused by the top 5 players

Example death commands.
Death-commands:
 - 'say %dragoneggdrop_dragon% has killed by %killer%!'
 - 'say %damagedtop_name_1% is the MVP of this battle'
 - 'say &e❖&6&l═&c&l─═─═─═─ &4Analysis &c&l─═─═─&6&l═&e❖'
 - 'say &7► %damagedtop_name_1% %damagedtop_percent_1%%'
 - 'say &7► %damagedtop_name_2% %damagedtop_percent_2%%'
 - 'say &7► %damagedtop_name_3% %damagedtop_percent_3%%'
 - 'say &7► %damagedtop_name_4% %damagedtop_percent_4%%'
 - 'say &7► %damagedtop_name_5% %damagedtop_percent_5%%'
 - 'eco give %damagedtop_name_1% 1000'
 - 'eco give %damagedtop_name_2% 600'
 - 'eco give %damagedtop_name_3% 400'
 - 'eco give %damagedtop_name_4% 300'
 - 'eco give %damagedtop_name_5% 200'

My players really like your plugin DragonEggDrop, thanks. :)

**Comment by 2008Choco** [comment]
Hadn't really considered hooking into Placeholder API but I don't see why I shouldn't. Having some sort of leaderboard system could be a really creative idea so yea, why not. While I'm at it, I may also add a hook for Maxim's placeholder API, [MVdWPlaceholderAPI](https://www.spigotmc.org/resources/mvdwplaceholderapi.11182/)

**Comment by 2008Choco** [comment]
Better late than never! Placeholder support for both PlaceholderAPI and MVdWPlaceholderAPI has been added in [b64660](https://github.com/2008Choco/DragonEggDrop/commit/b6466062f300d6577eb04ab2f4b2605615c9ea56). Will be available in a future version.
