### ISSUE TITLE
[Request] Custom dragon respawn message

### ISSUE THREAD

**Issue by momoservertw** [2008Choco/DragonEggDrop#19]
Please add an option for custom dragon respawn message.

**Comment by 2008Choco** [comment]
While testing the last version I found that it was lacking an option, yea. I'll throw this into the next release 😄

**Comment by momoservertw** [comment]
OK, waiting for your good news.
Thank you for reply. :)

**Comment by 2008Choco** [comment]
This option is long overdue, however...
