### ISSUE TITLE
Stop respawn countdown if a new dragon is spawned with endercrystals

### ISSUE THREAD

**Issue by Platinteufel** [2008Choco/DragonEggDrop#2]
If dragon-respawn is on cooldown and you spawn a new dragon with 4 endercrystals the actionbar respawn-countdown should stop as soon as the new dragon is alive.

**Comment by 2008Choco** [comment]
I will fix this in the next version! I hadn't thought of it. Clearly there are a bunch of other issues as well regarding existing dragons, so I'll see what I can do to fix it up a bit more

**Comment by Platinteufel** [comment]
Thanks! :) 👍 
This will happen if you spawn a new dragon and the cooldown hits 0:
https://youtu.be/NMQ5HkoZxZU
There are buggy endercrystals that can't be destroyed or replaced.

**Comment by 2008Choco** [comment]
This is likely because the old author didn't check if the dragon was present in the world before spawning a new one. I'll definitely make a fix for this :)
