### ISSUE TITLE
Could not pass event CreatureSpawnEvent to DragonEggDrop v1.6.1

### ISSUE THREAD

**Issue by stepech** [2008Choco/DragonEggDrop#20]
Hello, running latest spigot version (1.13.2) and latest Dragon egg drop version (1.6.1). Every time I try to spawn dragon via the plugin or via vanilla (crystals), it throws message "Could not pass event CreatureSpawnEvent to DragonEggDrop v1.6.1" and error code which you can see in the attached console log. Can you please help me with setting things up or by fixing the plugin? It just spwans vanilla dragon.
Last thing. Can you please add some option to set up XP we get from the dragon?
[latest.log](https://github.com/2008Choco/DragonEggDrop/files/2660099/latest.log)

**Comment by LeeTheTech** [comment]
Having the same issue: https://pastebin.com/8BRrGHSY

**Comment by 2008Choco** [comment]
md_5, in commit 20fc5b (December 5th, 2018), made some updates to Bukkit's mappings which is unusual as these are often done after major or minor releases, but this one was mid-version which really hurts developers. I'll have this resolved soon. I will publish a release most likely tomorrow addressing some issues from the latest build.

**Comment by 2008Choco** [comment]
A 1.13.2 update was dismissed, 1.14 support was added instead
