### ISSUE TITLE
Fresh install, nothing.

### ISSUE THREAD

**Issue by LukeSmith5853** [2008Choco/DragonEggDrop#22]
14.04 14:16:02 [Server] ERROR Could not pass event EntityDeathEvent to DragonEggDrop v1.6.1
14.04 14:16:02 [Server] INFO org.bukkit.event.EventException: null
14.04 14:16:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:573) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1205) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.EntityEnderDragon.dealDamage(EntityEnderDragon.java:535) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.EntityEnderDragon.a(EntityEnderDragon.java:507) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.EntityComplexPart.damageEntity(SourceFile:40) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.EntityArrow.b(EntityArrow.java:330) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.EntityArrow.a(EntityArrow.java:273) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.EntityArrow.tick(EntityArrow.java:198) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.EntityTippedArrow.tick(EntityTippedArrow.java:85) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1331) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.World.g(World.java:1298) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1132) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:968) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:16:02 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
14.04 14:16:02 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.EntityEnderDragon.ds()Lnet/minecraft/server/v1_13_R2/EnderDragonBattle;
14.04 14:16:02 [Server] INFO at com.ninjaguild.dragoneggdrop.nms.NMSUtils.getEnderDragonBattleFromDragon(NMSUtils.java:38) ~[?:?]
14.04 14:16:02 [Server] INFO at com.ninjaguild.dragoneggdrop.events.DragonLifeListeners.onDragonDeath(DragonLifeListeners.java:76) ~[?:?]
14.04 14:16:02 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
14.04 14:16:02 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
14.04 14:16:02 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
14.04 14:16:02 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
14.04 14:16:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot1.13.2.jar:git-Spigot-5629554-4c8327f]

**Comment by LukeSmith5853** [comment]
14.04 14:15:25 [Server] ERROR Could not pass event CreatureSpawnEvent to DragonEggDrop v1.6.1
14.04 14:15:25 [Server] INFO org.bukkit.event.EventException: null
14.04 14:15:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:446) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:383) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.World.addEntity(World.java:907) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.WorldServer.addEntity(WorldServer.java:917) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.World.addEntity(World.java:902) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.EnderDragonBattle.n(SourceFile:476) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.EnderDragonBattle.a(SourceFile:308) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.EnumDragonRespawn$4.a(SourceFile:80) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.EnderDragonBattle.b(SourceFile:233) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.WorldProviderTheEnd.l(SourceFile:129) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:582) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:968) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot1.13.2.jar:git-Spigot-5629554-4c8327f]
14.04 14:15:25 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
14.04 14:15:25 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.EntityEnderDragon.ds()Lnet/minecraft/server/v1_13_R2/EnderDragonBattle;
14.04 14:15:25 [Server] INFO at com.ninjaguild.dragoneggdrop.nms.NMSUtils.getEnderDragonBattleFromDragon(NMSUtils.java:38) ~[?:?]
14.04 14:15:25 [Server] INFO at com.ninjaguild.dragoneggdrop.events.DragonLifeListeners.onCreatureSpawn(DragonLifeListeners.java:48) ~[?:?]
14.04 14:15:25 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
14.04 14:15:25 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
14.04 14:15:25 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
14.04 14:15:25 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
14.04 14:15:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot1.13.2.jar:git-Spigot-5629554-4c8327f]

**Comment by 2008Choco** [comment]
See #20
