### ISSUE TITLE
Configurable experience for dragon templates

### ISSUE THREAD

**Issue by Myzumi** [2008Choco/DragonEggDrop#24]
I want to ask something about the custom dragons, i know some thinks already but what does 
"spawn-weight" do?

**Comment by 2008Choco** [comment]
https://github.com/2008Choco/DragonEggDrop/wiki/Creating-Custom-Dragons#spawn-weight

**Comment by Myzumi** [comment]
ok thanks, i have a question: is there a config option for xp drop? (like it drops 10xp level or something that you can define in the config)

**Comment by 2008Choco** [comment]
There is not and I'm not sure that's something I can change programmatically. I'll look more into it :)

**Comment by 2008Choco** [comment]
Unfortunately, dragons are a niche entity. The way they handle experience drops is entirely different from other entities and its values are hard-coded. Unless the server is patched and a change is made to CraftBukkit, this seems unlikely to be implemented. I apologize.

If, however, a change is made in the future, I will add a configuration option to have this be configurable. Until then, this issue will be closed.
