### ISSUE TITLE
1.15.1 support

### ISSUE THREAD

**Issue by TNTUP** [2008Choco/DragonEggDrop#25]
Heya Choco, fellow canadian friend o/

Tested current DED 1.7.0 on 1.15.1 and since it uses NMS, throws errors about "Packets". I tried forking and build it, but since I don't code java at all I gave up :( 

Happy late new year :D

**Comment by 2008Choco** [comment]
1.15 was added and released in the most recent version, 1.7.1 :)

**Comment by TNTUP** [comment]
You're the best! Take care <3
