### ISSUE TITLE
Console spam ender dragon (see screenshot)

### ISSUE THREAD

**Issue by TNTUP** [2008Choco/DragonEggDrop#27]
![welp](https://i.qcfb.ca/20200402170821.png)

Compiled your recent commits and using it now live throws those errors out while a player fights it

**Comment by 2008Choco** [comment]
It seems there's another plugin packaged `net.minemora` that makes changes to server internals and how entities are tracked. This is an issue with them, not DragonEggDrop.

**EDIT:** Perhaps [EntityTrackerFixer](https://www.spigotmc.org/resources/entitytrackerfixer-fix-1-14-4-1-15-entitytick-lag.70902/)? Send this issue to them instead.

**Comment by TNTUP** [comment]
> It seems there's another plugin packaged `net.minemora` that makes changes to server internals and how entities are tracked. This is an issue with them, not DragonEggDrop.
> 
> **EDIT:** Perhaps [EntityTrackerFixer](https://www.spigotmc.org/resources/entitytrackerfixer-fix-1-14-4-1-15-entitytick-lag.70902/)? Send this issue to them instead.

Yeah, using their plugin. Closing this *hugs Choco virtually*
