### ISSUE TITLE
Dragon Spamming Lightning and Loot Chest On Death

### ISSUE THREAD

**Issue by Rage-GitHub** [2008Choco/DragonEggDrop#29]
This plugin seems to keep causing issues no matter what, and one specifically where it seriously breaks the server and End. Whenever a player kills the Dragon the loot chest drops but then lightning and the loot in the chest are constantly being changed and randomized.

This is the error that is constantly spammed, even though you probably really can't make much from it.
```
[14:37:13 WARN]: [DragonEggDrop] Task #6597083 for DragonEggDrop v1.7.1 generated an exception
java.lang.NullPointerException: null
```

**Comment by 2008Choco** [comment]
This is resolved in a future version 😄 I just need to finish up some loose ends and I'll push an update.

**Comment by 2008Choco** [comment]
Update resolving this issue is available in a version to be released tonight. Please see DragonEggDrop 1.8.0
