### ISSUE TITLE
Loot Chest Full

### ISSUE THREAD

**Issue by Foulwerp** [2008Choco/DragonEggDrop#3]
If the loot chest becomes full, it crashes the server. 

Would suggest to add a check to see if chest is full, and an option to clear the chest before spawning new loot. 

I put elytra a non stackable item as loot killed the dragon a few times and the chest filled up, once full it would crash the server when trying to add loot to the full chest.

**Comment by 2008Choco** [comment]
o: that's interesting. I've never heard of that sort of thing crashing a server. As far as I'm aware, the Inventory#addItem() method returns a Map of items that could not be added to the chest. Nevertheless, I planned on reviewing the code for DragonEggDrop to fix various other issues as well. I will try to reproduce this issue and see what I can do

**Comment by Foulwerp** [comment]
Log of the server hanging and crashing. Not sure if it is useful.

https://pastebin.com/mURvxYgP

I am using paper spigot but I don't see that being the problem. It works fine until the chest is full and it cannot add another non stackable item.

**Comment by Foulwerp** [comment]
Decided to take a look for myself... 
Infinite loop if chest is full it subtracts from i then continues and adds to i over and over because the slot will never be null or air.

This is with the add one of all items to the chest.
```		
                for (int i = 0; i < lootItems.size(); i++) {
			int slot = rand.nextInt(chest.getBlockInventory().getSize());
			ItemStack slotItem = chest.getBlockInventory().getItem(slot);
			if (slotItem != null && slotItem.getType() != Material.AIR) {
				i--;
				continue;
			}
			chest.getBlockInventory().setItem(slot, lootItems.get(i));
		}

**Comment by 2008Choco** [comment]
You are correct. This is an infinite loop. According to the GitHub Blame for that file, it seems like some of NinjaStix's old code that I never bothered modifying. I'll fix that up when time is available to me. I'd say about 2 hours from now. Expect a release containing a fix either tonight or tomorrow
