### ISSUE TITLE
Placeholders in messages are not converting

### ISSUE THREAD

**Issue by CW-UK** [2008Choco/DragonEggDrop#33]
Placeholders used in the messages in any of the config files are not being converted, and instead just displaying the placeholder variable. Several people seem to be reporting the same thing in the discussion tab on spigotmc.org.

PlaceholderAPI is installed (latest version) and using latest version of Paper. Placeholders worked fine up until the latest update.

**Comment by 2008Choco** [comment]
Seems to be a common issue I may have just overlooked while implementing placeholders.
