### ISSUE TITLE
Error code, not sure what it means

### ISSUE THREAD

**Issue by Ellendyra** [2008Choco/DragonEggDrop#34]
> [Sun, 28. Jun 2020 12:11:16 EDT WARN] java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/44997612, uuid='6e91e393-93f1-4551-9b20-ac7a6c0cdff3', l='world_the_end', x=-34.14, y=86.33, z=-3.21, cx=0, cz=0, tl=0, v=false, d=false]
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1906)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at java.lang.reflect.Method.invoke(Method.java:498)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at java.lang.Thread.run(Thread.java:748)
[2:12 AM]
[Sun, 28. Jun 2020 12:11:16 EDT WARN] java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/44997613, uuid='9d0f471a-b45f-4557-8bb3-828c62851fb9', l='world_the_end', x=-38.05, y=86.34, z=-6.46, cx=0, cz=0, tl=0, v=false, d=false]
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1906)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at java.lang.reflect.Method.invoke(Method.java:498)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at java.lang.Thread.run(Thread.java:748)
[2:12 AM]
[Sun, 28. Jun 2020 12:11:16 EDT WARN] java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/44997611, uuid='d1720608-c128-44cd-b716-b445cf29d319', l='world_the_end', x=-33.41, y=86.38, z=-2.53, cx=0, cz=0, tl=0, v=false, d=false]
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1906)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at java.lang.reflect.Method.invoke(Method.java:498)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at java.lang.Thread.run(Thread.java:748)
[2:12 AM]
[Sun, 28. Jun 2020 12:11:16 EDT WARN] java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world_the_end: EntityComplexPart['Ender Dragon'/44997618, uuid='9899ed9c-b9e3-4f3c-a260-951e842a47dd', l='world_the_end', x=-33.77, y=88.34, z=-7.92, cx=0, cz=0, tl=0, v=false, d=false]
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1906)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at java.lang.reflect.Method.invoke(Method.java:498)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minemora.entitytrackerfixer.v1_15_R1.NMSEntityTracker.trackEntities(NMSEntityTracker.java:35)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.checkWorld(CheckTask.java:51)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minemora.entitytrackerfixer.v1_15_R1.tasks.CheckTask.run(CheckTask.java:30)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[Sun, 28. Jun 2020 12:11:16 EDT WARN]     at java.lang.Thread.run(Thread.java:748)

**Comment by 2008Choco** [comment]
Not the fault of DragonEggDrop. See #27
