### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by ahriee** [2008Choco/DragonEggDrop#5]
Hello, dragoneggdrop seems to be working fine prior to your recent 2 updates. Now everytime my server reloads, i am getting a version error for dragoneggdrop 1.4.1 
I believe i have download the latest version in spigot
Here's the error:
https://pastebin.com/Xg5ab6Kh

**Comment by 2008Choco** [comment]
Looks to me like temporary data isn't being read properly. I'll have this fixed by tonight and hopefully have another release ready

**Comment by Platinteufel** [comment]
Is there already a fix for this issue? It happens for me too in DED 1.4.1 and it's breaking the whole plugin. :(

**Comment by 2008Choco** [comment]
I'm going to take a look this Thanksgiving weekend and try to make a release sometime soon. I have no promises this weekend on a release, however. We'll have to see. Sorry this is taking as long as it is
